[book]
title = "juanfburgos"
authors = ["juanfburgos"]
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/fonts/fonts.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"

git-repository-url = "https://github.com/juanfburgos"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
